function lablz( xDataArg , xData , ystr , interpreter , fontname , fontsize )

switch xDataArg
    case 'time'
        xlabel('time (s)' , ...
            'Interpreter' , interpreter , ...
            'FontName' , fontname ,...
            'FontSize' , fontsize );
        
    case 'gait-cycle'
        xlabel('gait cycle (\%)' , ...
            'Interpreter' , interpreter , ...
            'FontName' , fontname ,...
            'FontSize' , fontsize );
        
end
xlim([xData(1) xData(end)])

ylabel( ystr , ...
            'Interpreter' , interpreter , ...
            'FontName' , fontname ,...
            'FontSize' , fontsize );

set( gca, ...
        'FontName' , fontname ,...
        'FontSize' , fontsize );


end